export const SpeachRecognitionLanguages = {
    "Afrikaans(af-ZA)": "af-ZA",
    "አማርኛ(am-ET)": "am-ET",
    "Azərbaycanca(az-AZ)": "az-AZ",
    "বাংলা বাংলাদেশ(bn-BD)": "bn-BD",
    "বাংলা ভারত(bn-IN)": "bn-IN",
    "Bahasa Indonesia(id-ID)": "id-ID",
    "Bahasa Melayu(ms-MY)": "ms-MY",
    "Català(ca-ES)": "ca-ES",
    "Čeština(cs-CZ)": "cs-CZ",
    "Dansk(da-DK)": "da-DK",
    "Deutsch(de-DE)": "de-DE",
    "English Australia(en-AU)": "en-AU",
    "English Canada(en-CA)": "en-CA",
    "English India(en-IN)": "en-IN",
    "English Kenya(en-KE)": "en-KE",
    "English Tanzania(en-TZ)": "en-TZ",
    "English Ghana(en-GH)": "en-GH",
    "English New Zealand(en-NZ)": "en-NZ",
    "English Nigeria(en-NG)": "en-NG",
    "English South Africa(en-ZA)": "en-ZA",
    "English Philippines(en-PH)": "en-PH",
    "English United Kingdom(en-GB)": "en-GB",
    "English United States(en-US)": "en-US",
    "Español Argentina(es-AR)": "es-AR",
    "Español Bolivia(es-BO)": "es-BO",
    "Español Chile(es-CL)": "es-CL",
    "Español Colombia(es-CO)": "es-CO",
    "Español Costa Rica(es-CR)": "es-CR",
    "Español Ecuador(es-EC)": "es-EC",
    "Español El Salvador(es-SV)": "es-SV",
    "Español España(es-ES)": "es-ES",
    "Español Estados Unidos(es-US)": "es-US",
    "Español Guatemala(es-GT)": "es-GT",
    "Español Honduras(es-HN)": "es-HN",
    "Español México(es-MX)": "es-MX",
    "Español Nicaragua(es-NI)": "es-NI",
    "Español Panamá(es-PA)": "es-PA",
    "Español Paraguay(es-PY)": "es-PY",
    "Español Perú(es-PE)": "es-PE",
    "Español Puerto Rico(es-PR)": "es-PR",
    "Español República Dominicana(es-DO)": "es-DO",
    "Español Uruguay(es-UY)": "es-UY",
    "Español Venezuela(es-VE)": "es-VE",
    "Euskara(eu-ES)": "eu-ES",
    "Filipino(fil-PH)": "fil-PH",
    "Français(fr-FR)": "fr-FR",
    "Basa Jawa(jv-ID)": "jv-ID",
    "Galego(gl-ES)": "gl-ES",
    "ગુજરાતી(gu-IN)": "gu-IN",
    "Hrvatski(hr-HR)": "hr-HR",
    "IsiZulu(zu-ZA)": "zu-ZA",
    "Íslenska(is-IS)": "is-IS",
    "Italiano Italia(it-IT)": "it-IT",
    "Italiano Svizzera(it-CH)": "it-CH",
    "ಕನ್ನಡ(kn-IN)": "kn-IN",
    "ភាសាខ្មែរ(km-KH)": "km-KH",
    "Latviešu(lv-LV)": "lv-LV",
    "Lietuvių(lt-LT)": "lt-LT",
    "മലയാളം(ml-IN)": "ml-IN",
    "मराठी(mr-IN)": "mr-IN",
    "Magyar(hu-HU)": "hu-HU",
    "ລາວ(lo-LA)": "lo-LA",
    "Nederlands(nl-NL)": "nl-NL",
    "नेपाली भाषा(ne-NP)": "ne-NP",
    "Norsk bokmål(nb-NO)": "nb-NO",
    "Polski(pl-PL)": "pl-PL",
    "Português Brasil(pt-BR)": "pt-BR",
    "Português Portugal(pt-PT)": "pt-PT",
    "Română(ro-RO)": "ro-RO",
    "සිංහල(si-LK)": "si-LK",
    "Slovenščina(sl-SI)": "sl-SI",
    "Basa Sunda(su-ID)": "su-ID",
    "Slovenčina(sk-SK)": "sk-SK",
    "Suomi(fi-FI)": "fi-FI",
    "Svenska(sv-SE)": "sv-SE",
    "Kiswahili Tanzania(sw-TZ)": "sw-TZ",
    "Kiswahili Kenya(sw-KE)": "sw-KE",
    "ქართული(ka-GE)": "ka-GE",
    "Հայերեն(hy-AM)": "hy-AM",
    "தமிழ் இந்தியா(ta-IN)": "ta-IN",
    "தமிழ் சிங்கப்பூர்(ta-SG)": "ta-SG",
    "தமிழ் இலங்கை(ta-LK)": "ta-LK",
    "தமிழ் மலேசியா(ta-MY)": "ta-MY",
    "తెలుగు(te-IN)": "te-IN",
    "Tiếng Việt(vi-VN)": "vi-VN",
    "Türkçe(tr-TR)": "tr-TR",
    "اُردُو پاکستان(ur-PK)": "ur-PK",
    "اُردُو بھارت(ur-IN)": "ur-IN",
    "Ελληνικά(el-GR)": "el-GR",
    "български(bg-BG)": "bg-BG",
    "Pусский(ru-RU)": "ru-RU",
    "Српски(sr-RS)": "sr-RS",
    "Українська(uk-UA)": "uk-UA",
    "한국어(ko-KR)": "ko-KR",
    "中文 普通话 (中国大陆)(cmn-Hans-CN)": "cmn-Hans-CN",
    "中文 普通话 (香港)(cmn-Hans-HK)": "cmn-Hans-HK",
    "中文 中文 (台灣)(cmn-Hant-TW)": "cmn-Hant-TW",
    "中文 粵語 (香港)(yue-Hant-HK)": "yue-Hant-HK",
    "日本語(ja-JP)": "ja-JP",
    "हिन्दी(hi-IN)": "hi-IN",
    "ภาษาไทย(th-TH)": "th-TH",

} as const
export type SpeachRecognitionLanguages = typeof SpeachRecognitionLanguages[keyof typeof SpeachRecognitionLanguages];
